OrdererOrgs:
  - Name: Orderer0
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer0
      - Hostname: peer1

#    Template:
#      Count: 1
    Users:
      Count: 1
  
  - Name: Org2
    Domain: org2.example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer0
      - Hostname: peer1

#    Template:
#      Count: 1
    Users:
      Count: 1
