version: '2'

services:
  ca-base:
    image: hyperledger/fabric-ca:$CAIMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca1.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/3874173ba4f12ab8154cba23de4db6674d4eb9f112399882f2d92a40661097fb_sk

      #- FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      #- FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c547457fd5fa62952310b2a71ee87ad599ed7a82dc550082dc471cd45372e640_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/tlsca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/77b1d864abe8a9103ac670490de262f8e0a91b1e2b3ed5c39df5ca2bccf4e091_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    volumes:
      - ../crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../crypto-config/peerOrganizations/org1.example.com/tlsca/:/etc/hyperledger/fabric-ca-server-config/tlsca
      - ../crypto-config/peerOrganizations/org1.example.com/msp:/etc/hyperledger/fabric-ca-server-config/msp
      - ../crypto-config/peerOrganizations/org1.example.com/users/:/etc/hyperledger/fabric-ca-server-config/users
      - ../crypto-config/peerOrganizations/org1.example.com/tlsca/77b1d864abe8a9103ac670490de262f8e0a91b1e2b3ed5c39df5ca2bccf4e091_sk:/etc/hyperledger/fabric-ca-server/msp/keystore/key.pem
#    command: > 
#      sh -c "cp /etc/hyperledger/fabric-ca-server-config/*_sk /etc/hyperledger/fabric-ca-server/msp/keystore/key.pem &&
#             sleep 5 &&
#             ls /etc/hyperledger/fabric-ca-server/msp/keystore/ &&
#             sleep 10 &&
#             fabric-ca-server start -b admin:adminpw -d"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    #command: sh -c 'fabric-ca-server start --ca.name ca.example.com --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/3874173ba4f12ab8154cba23de4db6674d4eb9f112399882f2d92a40661097fb_sk -b admin:adminpw -d'
    #command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/3874173ba4f12ab8154cba23de4db6674d4eb9f112399882f2d92a40661097fb_sk -b admin:adminpw -d'  


